/**
 * 把 MySQL 的 CREATE TABLE 语句转换为 Postgres 兼容的语句。
 * 覆盖常见类型；复杂情况（enum / 外键 / 生成列）会给出 warning。
 */

export interface ConvertResult {
    sql: string
    warnings: string[]
}

export function convertMySQLToPostgres(mysqlDDL: string): ConvertResult {
    const warnings: string[] = []
    let sql = mysqlDDL

    // 1. 去掉反引号
    sql = sql.replace(/`/g, '')

    // 2. AUTO_INCREMENT（必须最先处理，否则会被后续 int(n) 规则拆掉）
    sql = sql.replace(
        /\bint(?:\(\d+\))?\s+NOT NULL\s+AUTO_INCREMENT\b/gi,
        'bigint GENERATED BY DEFAULT AS IDENTITY'
    )
    sql = sql.replace(
        /\bint(?:\(\d+\))?\s+AUTO_INCREMENT\b/gi,
        'bigint GENERATED BY DEFAULT AS IDENTITY'
    )

    // 3. tinyint(1) / tinyint(n) → smallint（在 int(n) 之前处理）
    sql = sql.replace(/\btinyint\(\d+\)/gi, 'smallint')

    // 4. int(1) → smallint（在 int(n) 之前处理）
    sql = sql.replace(/\bint\(1\)/gi, 'smallint')

    // 5. 其余 int(n) → integer
    sql = sql.replace(/\bint\(\d+\)/gi, 'integer')

    // 6. datetime → timestamptz
    sql = sql.replace(/\bdatetime\b/gi, 'timestamptz')

    // 7. decimal → numeric
    sql = sql.replace(/\bdecimal\b/gi, 'numeric')

    // 8. float → real
    sql = sql.replace(/\bfloat\b/gi, 'real')

    // 9. double（不含 double precision）→ double precision
    sql = sql.replace(/\bdouble\b(?!\s+precision)/gi, 'double precision')

    // 10. 默认值去引号：DEFAULT '数字' → DEFAULT 数字
    sql = sql.replace(/DEFAULT\s+'(\d+)'/gi, 'DEFAULT $1')

    // 11. 提取 PRIMARY KEY (col)，转成 inline 或表尾定义
    const pkMatch = sql.match(/,\s*PRIMARY KEY\s*\(([^)]+)\)/i)
    if (pkMatch) {
        const pkCols = pkMatch[1].replace(/`/g, '').trim()
        // 从 CREATE TABLE 里删掉单独定义的 PRIMARY KEY
        sql = sql.replace(/,\s*PRIMARY KEY\s*\([^)]+\)/gi, '')

        if (!pkCols.includes(',')) {
            // 单列主键：inline 加到该列后面
            const pkRegex = new RegExp(
                `(\\b${pkCols}\\b\\s+[^,\\n]+?)(,|\\n)`,
                'i'
            )
            sql = sql.replace(pkRegex, '$1 PRIMARY KEY$2')
        } else {
            // 复合主键：放在表定义尾部
            sql = sql.replace(/\n\s*\)/, `,\n  PRIMARY KEY (${pkCols})\n)`)
        }
    }

    // 12. 提取 KEY xxx (col)，生成独立的 CREATE INDEX
    const indexes: string[] = []
    const keyRegex = /,\s*KEY\s+(\w+)\s*\(([^)]+)\)/gi
    let m: RegExpExecArray | null
    while ((m = keyRegex.exec(sql)) !== null) {
        const indexName = m[1]
        const cols = m[2].replace(/`/g, '').trim()
        indexes.push(`CREATE INDEX idx_${indexName} ON <TABLE> (${cols});`)
    }
    sql = sql.replace(/,\s*KEY\s+\w+\s*\([^)]+\)/gi, '')

    // 13. 删除 ENGINE / CHARSET / COLLATE 结尾
    sql = sql.replace(/\)\s*ENGINE=\w+[^;]*/gi, ')')

    // 14. 兼容性检查
    if (/\benum\s*\(/i.test(sql)) {
        warnings.push(
            'ENUM 类型需要手动处理：Postgres 需要先 CREATE TYPE，或改成 text + CHECK。'
        )
    }
    if (/\bfulltext\s+key/i.test(sql)) {
        warnings.push('FULLTEXT KEY 在 Postgres 不支持，需要改用 GIN / tsvector。')
    }
    if (/\bunsigned\b/i.test(sql)) {
        warnings.push('UNSIGNED 在 Postgres 不支持，请改用 CHECK (col >= 0)。')
    }
    if (/0000-00-00/.test(sql)) {
        warnings.push(
            '检测到 0000-00-00 日期：Postgres 不接受，需在数据中替换为空值。'
        )
    }

    // 15. 补分号
    if (!sql.trim().endsWith(';')) sql = sql.trim() + ';'

    // 16. 替换索引占位表名
    const tableMatch = mysqlDDL.match(/CREATE TABLE\s+`?(\w+)`?/i)
    const tableName = tableMatch ? tableMatch[1] : 'unknown'
    const indexSQL = indexes
        .map((i) => i.replace('<TABLE>', tableName))
        .join('\n')

    const finalSQL = indexSQL ? `${sql}\n\n${indexSQL}` : sql

    return { sql: finalSQL, warnings }
}